django_zoook/urls.py
# -*- coding: utf-8 -*-
############################################################################################
#
#    Zoook. OpenERP e-sale, e-commerce Open Source Management Solution
#    Copyright (C) 2011 Zikzakmedia S.L. (<http://www.zikzakmedia.com>). All Rights Reserved
#    $Id$
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
############################################################################################

import re

from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib.sitemaps import GenericSitemap

from django_zoook.views import index, doc
from django_zoook.search.views import search
from django_zoook.tag.views import keyword
from django_zoook.sitemaps import sitemaps
from django_zoook.transurl import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

js_info_dict = {
    'packages': ('django.conf',
                 'django.contrib.admin',
                ),
}

urlpatterns = patterns('',
    #url(r"^$", index, name='index'),
    url(r"^$", doc, name='index'),

    # catalog 
    url(r"^%s/" % catalog_url['en'], include("django_zoook.catalog.urlsCatalog")),
    url(r"^%s/"% catalog_url['es'], include("django_zoook.catalog.urlsCatalog")),
    url(r"^%s/"% catalog_url['ca'], include("django_zoook.catalog.urlsCatalog")),

    # catalog manage
    url(r'^catalogmanage/', include('django_zoook.catalog.urlsCatalogManage')),

    # manufacturer 
    url(r"^%s/" % manufacturer_url['en'], include("django_zoook.catalog.urlsManufacturer")),
    url(r"^%s/" % manufacturer_url['es'], include("django_zoook.catalog.urlsManufacturer")),
    url(r"^%s/" % manufacturer_url['ca'], include("django_zoook.catalog.urlsManufacturer")),

    # product 
    url(r"^%s/" % product_url['en'], include("django_zoook.catalog.urlsProduct")),
    url(r"^%s/" % product_url['es'], include("django_zoook.catalog.urlsProduct")),
    url(r"^%s/" % product_url['ca'], include("django_zoook.catalog.urlsProduct")),

    # contact
    url(r"^%s/" % contact_url['en'], include("django_zoook.contact.urlsContact")),
    url(r"^%s/" % contact_url['es'], include("django_zoook.contact.urlsContact")),
    url(r"^%s/" % contact_url['ca'], include("django_zoook.contact.urlsContact")),

    # Search
    #url(r'^search/', include('haystack.urls')),
    url(r"^search", search, name='search'),

    # Tag
    url(r"^tag/(?P<tag>[^/]+)/$", keyword, name='tag'),

    url(r"^partner/", include("django_zoook.partner.urlsPartner")),
    url(r"^sale/", include("django_zoook.sale.urlsSale")),
    url(r"^account/", include("django_zoook.account.urlsAccount")),
    url(r"^payment/", include("django_zoook.payment.urlsPayment")),
    url(r"^base/", include("django_zoook.base.urlsBase")),

    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

    # Ajax Paths
    url(r'^filemanager/', include('django_zoook.tools.filemanager.connector.urls')),
    url(r'^inplaceeditform/', include('inplaceeditform.urls')),
    url(r'^jsi18n$', 'django.views.i18n.javascript_catalog', js_info_dict),

    # Admin 
    url(r'^manager/', include(admin.site.urls)),
    url(r'^filebrowser/', include('filebrowser.urls')),

    #  Blog
    url(r"^blog/", include("django_zoook.blog.urlsBlog")),

    # Cms
    url(r"^cms/", include("django_zoook.tools.cms.urlsCms")),

    # Content
    url(r"^content/", include("django_zoook.content.urlsContent")),
)

if settings.STATICFILES_IGNORE_DEBUG:
    urlpatterns += patterns('',
            url(r'^%s(?P<path>.*)$' % re.escape(settings.STATIC_URL.lstrip('/')), 'staticsfiles_ignoredebug.views.serve'),
        )

django_zoook/contact/models.py
# -*- coding: utf-8 -*-
############################################################################################
#
#    Zoook. OpenERP e-sale, e-commerce Open Source Management Solution
#    Copyright (C) 2011 Zikzakmedia S.L. (<http://www.zikzakmedia.com>). All Rights Reserved
#    $Id$
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
############################################################################################

from django.db import models
from django.utils.translation import get_language, ugettext_lazy as _
from django import forms

from transmeta import TransMeta
from django_zoook.transurl import contact_url

from django_zoook.settings import LOCALE_URI

class Contact(models.Model):
    """Contact Model"""
    __metaclass__ = TransMeta

    name = models.CharField(_('Name'), max_length=128)
    slug = models.SlugField(_('slug'), max_length=128, unique=True, help_text=_("This is a unique identifier that allows your contacts to display its detail view, ex 'how-can-i-contribute'"))
    default = models.BooleanField(_('Default'), default=False)
    email = models.CharField(_('Email'), max_length=128, blank=True)
    show_email = models.BooleanField(_('Show Email'), default=False)
    street = models.TextField(_('Street'), null=True, blank=True)
    zip = models.CharField(_('Zip'), max_length=128, null=True, blank=True)
    city = models.CharField(_('City'), max_length=128, null=True, blank=True)
    country = models.CharField(_('Country'), max_length=128, null=True, blank=True)
    phone = models.CharField(_('Phone'), max_length=128, null=True, blank=True)
    mobile_phone = models.CharField(_('Mobile Phone'), max_length=128, null=True, blank=True)
    fax = models.CharField(_('Fax'), max_length=128, null=True, blank=True)
    utm = models.CharField(_('UTM'), max_length=128, null=True, blank=True)
    twitter = models.CharField(_('Twitter'), max_length=128, null=True, blank=True)
    misc = models.TextField(_('Miscellaneous'), null=True, blank=True)
    status = models.BooleanField(_('Status'), default=False)
    logo  = models.ImageField(upload_to='contact/', blank=True, help_text=_("Resize image. Check documentation about logo template"))

    """ Custom fields model """

    class Meta:
        db_table = 'contact_contacts'
        verbose_name = _('contact')
        verbose_name_plural = _('contacts')

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        if LOCALE_URI:
            url = '/%s/%s/%s' % (get_language(), contact_url[get_language()], self.slug)
        else:
            url = '/%s/%s' % (contact_url[get_language()], self.slug)
        return url

class ContactForm(forms.Form):
    """Contact Form"""
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    contact_text = forms.CharField(widget=forms.Textarea)

django_zoook/partner/models.py
# -*- coding: utf-8 -*-
############################################################################################
#
#    Zoook. OpenERP e-sale, e-commerce Open Source Management Solution
#    Copyright (C) 2011 Zikzakmedia S.L. (<http://www.zikzakmedia.com>). All Rights Reserved
#    $Id$
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
############################################################################################

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django import forms

from transmeta import TransMeta

'''OpenERP Models'''
class ResPartnerTitle(models.Model):
    """Partner Title OpenERP"""
    __metaclass__ = TransMeta

    name = models.CharField(_('name'), max_length=64)
    shortcut = models.CharField(_('shortcut'), max_length=16)
    update_price = models.BooleanField(_('update price'))

    class Meta:
        db_table = 'res_partner_title'
        verbose_name = _('partner title')
        verbose_name_plural = _('partner titles')
        translate = (
            'name',
            'shortcut',
            )

    def __unicode__(self):
        return self.name

class AuthProfile(models.Model):
    """Partner"""
    user = models.ForeignKey(User, verbose_name="User", related_name="user_profile_s", unique=True, null=True, blank=True)
    partner_id = models.IntegerField(null=True, blank=True)

class PartnerForm(forms.Form):
    """Partner Form"""
    name = forms.CharField(max_length=128)
    vat_code = forms.CharField(max_length=2)
    vat = forms.CharField(max_length=32)
    street = forms.CharField(max_length=128)
    zip = forms.CharField(max_length=32)
    city = forms.CharField(max_length=128)

django_zoook/partner/templates/partner/changepassword.html
{% extends "layout.html" %}
{% load i18n %}

{% block head %}
    <link href="{{ STATIC_URL }}css/{{ THEME }}/user.css" rel="stylesheet" type="text/css" media="screen">
    <link href="{{ STATIC_URL }}css/{{ THEME }}/form.css" rel="stylesheet" type="text/css" media="screen">
{% endblock %}

{% block content %}
<div class="primary-content span-12 last changepassword">

{% include 'partner/menu.html' %}

<h2>{{ title }}</h2>

{% if error %}
    {% if error %}<div id="message" class="msg-info">{{ error }}</div>{% endif %}
{% endif %}

<p>{% trans "Insert your new password" %}:</p>
<form method="post" action="{% url partner_changepassword %}">
    <table>
        <tbody>
	        <tr>
	            <td>{{ form.password1.label }}</td>
	            <td><input type="password" name="password1" id="id_password1" class="required" minlength="6"/></td>
	        </tr>
	        <tr>
	            <td>{{ form.password2.label }}</td>
	            <td><input type="password" name="password2" id="id_password2" class="required" minlength="6"/></td>
	        </tr>
	        <tr>
	            <td>
	                <input type="submit" class="btn-action" value="{% trans "Change password" %}" />
	            </td>
	        </tr>
        </tbody>
    </table>
    {% csrf_token %}
</form>

</div>
{% endblock %}

django_zoook/partner/templates/partner/error.html
{% extends "layout.html" %}
{% load i18n %}

{% block head %}
    <link href="{{ STATIC_URL }}css/{{ THEME }}/user.css" rel="stylesheet" type="text/css" media="screen">
{% endblock %}

{% block content %}
<div class="primary-content span-12 last">
    <div class="msg-warning">{{ error }}</div>
</div>
{% endblock %}

django_zoook/partner/templates/partner/menu.html
{% load i18n %}

<ul id="menu-profile">
    <li><a href="{% url sale %}" title="{% trans "Orders" %}">{% trans "Orders" %}</a></li>
    <li><a href="{% url account %}" title="{% trans "Invoice" %}">{% trans "Invoices" %}</a></li>
    <li><a href="{% url partner_partner %}" title="{% trans "Account" %}">{% trans "Your account" %}</a></li>
    <li><a href="{{ LOCALE_URI }}/{% trans 'catalog' %}/wishlist/" title="{% trans "My Wishlist" %}">{% trans "My Wishlist" %}</a></li>
    <li><a href="{% url partner_changepassword %}" title="{% trans "Change password" %}">{% trans "Change password" %}</a></li>
    <li><a href="{% url partner_logout %}" title="{% trans "Logout" %}">{% trans "Logout" %}</a></li>
</ul>

django_zoook/partner/templates/partner/partner.html
{% extends "layout.html" %}
{% load i18n %}

{% block head %}
    <link href="{{ STATIC_URL }}css/{{ THEME }}/form.css" rel="stylesheet" type="text/css" media="screen">
    <link href="{{ STATIC_URL }}css/{{ THEME }}/user.css" rel="stylesheet" type="text/css" media="screen">
    <script src="{{ STATIC_URL }}js/jquery.validate.min.js" type="text/javascript"></script>
    {% if request.LANGUAGE_CODE != 'en' %}
    	<script src="{{ STATIC_URL }}js/localization/messages_{{ request.LANGUAGE_CODE }}.js" type="text/javascript"></script>
    {% endif %}
{% endblock %}

{% block content %}
<div id="page-wrap" class="clearfix">
    {% include 'partner/menu.html' %}
    <div id="partner-details">
		{% if message %}
		    <div id="message" class="msg-info">
		        <h3>
		        {% for msg in message %}
		           {{ msg }}<br/>
		        {% endfor %}
		        </h3>
		    </div>
		{% endif %}
        <h1>{{title}}</h1>

		<form action="{% url partner_partner %}" method="post" id="partnerForm">
			<fieldset>
			    <div class="col2-set">
					<div class="new-users">
					<ul class="noeditable">
		            	<h3>{% trans "Customer Information" %}</h3>
		                <li>
		                    <label for="id_name">{% trans "Full Name" %}</label>
		                    <strong>{{ partner.name }}</strong>
		                </li>
                        <li>
                            <label for="email">{% trans "Email" %}</label>
                            <span>{{ user.email }}</span>
                        </li>
		                <li>
		                    <label for="id_vat">{% trans "Vat" %}</label>
		                    <span>{{ vat }}&nbsp;</span>
		                </li>
		                {% if partnet_title %}
	                        <li>
	                            <label for="title">{% trans "You are ?" %}</label>
	                            <span>{{ partnet_title }}</span>
	                        </li>
                        {% endif %}
		            </ul>
		            {% if address_invoice|length = 0 %}{% trans "There are not invoice address available" %}{% endif %}
		            {% for invoice in address_invoice %}
		            <ul>
		                <h3>{% trans "Invoice Address" %}</h3>
		                <li>
		                    <label for="{{ invoice.id }}_street">{% trans "Address" %} <span class="required">*</span></label>
		                    <input type="text" name="{{ invoice.id }}_street" id="{{ invoice.id }}_street" maxlength="128" value="{{ invoice.street }}" class="required" minlength="6"/>
		                </li>
		                <li>
		                    <label for="{{ invoice.id }}_zip">{% trans "ZIP" %} <span class="required">*</span></label>
		                    <input type="text" name="{{ invoice.id }}_zip" id="{{ invoice.id }}_zip" maxlength="128" value="{{ invoice.zip }}" class="required" minlength="4"/>
		                </li>
                        <li>
                            <label for="{{ invoice.id }}_city">{% trans "City" %} <span class="required">*</span></label>
                            <input type="text" name="{{ invoice.id }}_city" id="{{ invoice.id }}_city" maxlength="128" value="{{ invoice.city }}" class="required" minlength="2"/>
                        </li>
                        <li>
                            <label for="{{ invoice.id }}_phone">{% trans "Phone" %}</label>
                            <input type="text" name="{{ invoice.id }}_phone" id="{{ invoice.id }}_phone" maxlength="30" value="{% if invoice.phone %}{{ invoice.phone }}{% endif %}" minlength="7"/>
                        </li>
		            </ul>
		            {% endfor %}
		            {% if address_delivery|length = 0 %}{% trans "There are not delivery address available" %}{% endif %}
			        {% for delivery in address_delivery %}
		            <ul id="delivery-address"{% if same_address %} style="display: none;"{% endif %}>
		                <h3>{% trans "Delivery Address" %}</h3>
		                <li>
		                    <label for="{{ delivery.id }}_street">{% trans "Address" %} <span class="required">*</span></label>
		                    <input type="text" name="{{ delivery.id }}_street" id="{{ delivery.id }}_street" maxlength="128" value="{{ delivery.street }}" class="required" minlength="6"{% if same_address %} disabled="disabled"{% endif %}/>
		                </li>
		                <li>
		                    <label for="{{ delivery.id }}_zip">{% trans "ZIP" %} <span class="required">*</span></label>
		                    <input type="text" name="{{ delivery.id }}_zip" id="{{ delivery.id }}_zip" maxlength="128" value="{{ delivery.zip }}" class="required" minlength="4"{% if same_address %} disabled="disabled"{% endif %}/>
		                </li>
		                <li>
		                    <label for="{{ delivery.id }}_city">{% trans "City" %} <span class="required">*</span></label>
		                    <input type="text" name="{{ delivery.id }}_city" id="{{ delivery.id }}_city" maxlength="128" value="{{ delivery.city }}" class="required" minlength="2"{% if same_address %} disabled="disabled"{% endif %}/>
		                </li>
                        <li>
                            <label for="{{ delivery.id }}_phone">{% trans "Phone" %}</label>
                            <input type="text" name="{{ delivery.id }}_phone" id="{{ delivery.id }}_phone" maxlength="30" value="{% if delivery.phone %}{{ delivery.phone }}{% endif %}" minlength="7"/>
                        </li>
		            </ul>
		            {% endfor %}
					</div>
				</div>
			    <div class="col2-set">
			        <div class="col-1">
			            <div class="buttons-set">
			            </div>
			        </div>
			        <div class="col-2">
			            <div class="buttons-set">
			                <input type="submit" value="{% trans "Save" %}" class="btn-action" />
			                <p class="comment"><span class="required">*</span> {% trans "Required Fields" %}</p>
			            </div>
			        </div>
			    </div>
			</fieldset>
			{% csrf_token %}
		</form>

    </div>
</div>
{% endblock %}
{% block jqueryload %}
    $("#partnerForm").validate();
{% endblock %}

django_zoook/partner/templates/partner/profile.html
{% extends "layout.html" %}
{% load i18n %}

{% block head %}<link href="{{ STATIC_URL }}css/{{ THEME }}/user.css" rel="stylesheet" type="text/css" media="screen">{% endblock %}

{% block content %}
<div id="page-wrap" class="clearfix">
    {% if message %}<div id="message">
        <h1>{{ message }}</h1>
    </div>{% endif %}
    {% include 'partner/menu.html' %}

    <div id="profile-content">
        <p>{% blocktrans %}Hello {{full_name}}.{% endblocktrans %}</p>

        <ul id="menu-profile-home">
            <li><a href="{% url sale %}" title="{% trans "Orders" %}">{% trans "Orders" %}</a></li>
            <li><a href="{% url account %}" title="{% trans "Invoices" %}">{% trans "Invoices" %}</a></li>
            <li><a href="{% url partner_partner %}" title="{% trans "Your acccount" %}">{% trans "Your account" %}</a></li>
            <li><a href="{% url partner_changepassword %}" title="{% trans "Change password" %}">{% trans "Change password" %}</a></li>
            <li><a href="{% url partner_logout %}" title="{% trans "Logout" %}">{% trans "Logout" %}</a></li>
        </ul>
    </div>
</div>
{% endblock %}

django_zoook/partner/templates/partner/register.html
{% extends "layout.html" %}
{% load i18n %}

{% block head %}
    <link href="{{ STATIC_URL }}css/{{ THEME }}/form.css" rel="stylesheet" type="text/css" media="screen">
    <link href="{{ STATIC_URL }}css/{{ THEME }}/user.css" rel="stylesheet" type="text/css" media="screen">
    <script src="{{ STATIC_URL }}js/jquery.validate.min.js" type="text/javascript"></script>
    {% if request.LANGUAGE_CODE != 'en' %}
    	<script src="{{ STATIC_URL }}js/localization/messages_{{ request.LANGUAGE_CODE }}.js" type="text/javascript"></script>
    {% endif %}

    <script type="text/javascript">
     var RecaptchaOptions = {
        theme : 'clean'
     };
     </script>
{% endblock %}

{% block content %}
<div class="primary-content span-12 last">

<div id="top-header">{% trans "Create an account." %}</div>

{% if message %}
    <div id="message" class="msg-error">
        <h1>
	        {% for msg in message %}
	           {{ msg }}<br/>
	        {% endfor %}
        </h1>
    </div>
{% endif %}

<form action="{% url partner_register %}" method="post" id="registerForm">
<fieldset>
    <div class="col2-set">
        <div class="new-users">
            <h1>{% trans "New customers" %}</h1>
            <ul>
            	<h3>{% trans "User Information" %}</h3>
                <li>
                    <label for="id_username">{{ form.username.label }} <span class="required">*</span></label>
                    <input type="text" name="username" id="id_username" maxlength="30" value="{{ username }}" class="required" minlength="6"/> (az09)
                </li>
                <li class="register-field">
                    <label for="id_email">{% trans "Email" %} <span class="required">*</span></label>
                    <input type="text" name="email" id="id_email" value="{{ email }}" class="required email"/>
                </li>
                <li class="register-field">
                    <label for="id_password1">{{ form.password1.label }} <span class="required">*</span></label>
                    <input type="password" name="password1" id="id_password1" class="required" minlength="6"/>
                </li>
                <li class="register-field">
                    <label for="id_password2">{{ form.password2.label }} <span class="required">*</span></label>
                    <input type="password" name="password2" id="id_password2" class="required" minlength="6"/>
                </li>
            </ul>
            <ul>
            	<h3>{% trans "Customer Information" %}</h3>
                <li>
                    <label for="id_name">{% trans "Full Name" %} <span class="required">*</span></label>
                    <input type="text" name="name" id="id_name" maxlength="128" value="{{ name }}" class="required" minlength="6"/>
                </li>
                <li>
                	<label for="vat_code">{% trans "Country" %} <span class="required">*</span></label>
                    <select name="vat_code" id="vat_code" class="vat_code">
                    {% for country in countries %}<option value="{{ country.code }}" {% if country.code == country_default %} selected="selected"{% endif %}>{{ country.name }}</option>{% endfor %}
                    </select>
                </li>
                {% if titles|length >= 0 %}
	                <li>
	                    <label for="title">{% trans "You are ?" %}</label>
	                    <select name="title" id="title" class="title">
	                        <option value=""></option>
	                        {% for title in titles %}<option value="{{ title.id }}" {% ifequal title.id|slugify title_default %} selected="selected"{% endifequal %}>{{ title.name }}</option>{% endfor %}
	                    </select>
	                </li>
                {% endif %}
                <li>
                    <label for="id_vat">{% trans "Vat" %} {% if partner_vat_required %}<span class="required">*</span>{% endif %}</label>
                    <input type="text" name="vat" id="id_vat" maxlength="128" value="{{ vat }}" {% if partner_vat_required %}class="required"{% endif %} minlength="6"/>
                </li>
            </ul>
            <ul>
                <h3>{% trans "Invoice Address" %}</h3>
                <li>
                    <label for="id_street">{% trans "Address" %} <span class="required">*</span></label>
                    <input type="text" name="street" id="id_street" maxlength="128" value="{{ street }}" class="required" minlength="6"/>
                </li>
                <li>
                    <label for="id_zip">{% trans "ZIP" %} <span class="required">*</span></label>
                    <input type="text" name="zip" id="id_zip" maxlength="128" value="{{ zip }}" class="required" minlength="4"/>
                </li>
                <li>
                    <label for="id_city">{% trans "City" %} <span class="required">*</span></label>
                    <input type="text" name="city" id="id_city" maxlength="128" value="{{ city }}" class="required" minlength="2"/>
                </li>
                <li>
                    <label for="id_phone">{% trans "Phone" %}</label>
                    <input type="text" name="phone" id="id_phone" maxlength="128" value="{{ phone }}" minlength="7"/>
                </li>
                <li>
                	<input type="checkbox" name="delivery-same-address" {% if same_address %} checked="checked"{% endif %} />
                	<label for="delivery-same-address"><i>{% trans "Same address for delivery" %}</i></label>
                </li>
            </ul>
            <ul id="delivery-address"{% if same_address %} style="display: none;"{% endif %}>
                <h3>{% trans "Delivery Address" %}</h3>
                <li>
                    <label for="delivery_id_street">{% trans "Address" %} <span class="required">*</span></label>
                    <input type="text" name="delivery_street" id="delivery_id_street" maxlength="128" value="{{ delivery_street }}" class="required" minlength="6"{% if same_address %} disabled="disabled"{% endif %}/>
                </li>
                <li>
                    <label for="delivery_id_zip">{% trans "ZIP" %} <span class="required">*</span></label>
                    <input type="text" name="delivery_zip" id="delivery_id_zip" maxlength="128" value="{{ delivery_zip }}" class="required" minlength="4"{% if same_address %} disabled="disabled"{% endif %}/>
                </li>
                <li>
                    <label for="delivery_id_city">{% trans "City" %} <span class="required">*</span></label>
                    <input type="text" name="delivery_city" id="delivery_id_city" maxlength="128" value="{{ delivery_city }}" class="required" minlength="2"{% if same_address %} disabled="disabled"{% endif %}/>
                </li>
                <li>
                    <label for="delivery_id_phone">{% trans "Phone" %}</label>
                    <input type="text" name="delivery_phone" id="delivery_id_phone" maxlength="128" value="{{ delivery_phone }}" minlength="7"/>
                </li>
            </ul>
        </div>
        {% if html_captcha %}
        <div class="col-2 register-users">
            <h3>{% trans "To create an Account insert the same number" %}</h3>
            {{ html_captcha|safe }}
        </div>
        {% endif %}
    </div>
    <div class="col2-set">
        <div class="col-1">
            <div class="buttons-set">
            </div>
        </div>
        <div class="col-2">
            <div class="buttons-set">
                <input type="submit" value="{% trans "Create new account" %}" class="btn-action" />
                <p class="comment"><span class="required">*</span> {% trans "Required Fields" %}</p>
            </div>
        </div>
    </div>
</fieldset>
{% if redirect %}<input type="hidden" value="{{ redirect }}" name="redirect"/>{% endif %}
{% csrf_token %}
</form>

</div>
{% endblock %}
{% block jqueryload %}
    $("#registerForm").validate();

	$('input[name=delivery-same-address]').change(function() {
		if($(this).is(':checked')) {
			$('#delivery-address').hide();
			$('#delivery-address input').attr('disabled', 'disabled');
		} else {
			$('#delivery-address').show();
			$('#delivery-address input').removeAttr('disabled');
		}
	});
{% endblock %}

django_zoook/partner/templates/partner/remember.html
{% extends "layout.html" %}
{% load i18n %}

{% block head %}
    <link href="{{ STATIC_URL }}css/{{ THEME }}/user.css" rel="stylesheet" type="text/css" media="screen">
    <link href="{{ STATIC_URL }}css/{{ THEME }}/form.css" rel="stylesheet" type="text/css" media="screen">

    <script type="text/javascript">
     var RecaptchaOptions = {
        theme : 'clean'
     };
     </script>
{% endblock %}

{% block content %}
<div class="primary-content span-12 last remember">


{% if message %}
    <div id="message" class="msg-info">
        <h3>
        {% for msg in message %}
           {{ msg }}<br/>
        {% endfor %}
        </h3>
    </div>
{% endif %}

<p>{% trans "Insert your email and username and new password are you send it" %}.</p>
<form method="post" action="{{ LOCALE_URI }}/partner/remember/">
    <table>
        <tr> 
            <td><label for="id_email">{% trans "Email" %}</label></td> 
            <td><input type="text" name="email" id="id_email" value="{{ email }}" /></td> 
        </tr> 
        <tr><td colspan="2">{{ html_captcha|safe }}</td></tr>
        <tr>
            <td>
                <input type="submit" class="btn-action" value="{% trans "Submit" %}" />
            </td>
        </tr>
    </table>
    {% csrf_token %}
</form>

</div>
{% endblock %}